<a href="https://colab.research.google.com/github/sevvalyildiz/DeepLearning/blob/master/RECFEA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings   
from IPython.display import display, HTML

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (0.24.2)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.5.3)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.16.4)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)

In [0]:
from google.colab import files
files.upload()

Saving abuyss.dat to abuyss.dat

In [0]:
a_df=pd.read_csv('abuyss.dat')

In [0]:
a_df

         sessionid                 timestamp     itemid  price  quantity
0           420374  2014-04-06T18:44:58.314Z  214537888  12462         1
1           420374  2014-04-06T18:44:58.325Z  214537850  10471         1
2           281626  2014-04-06T09:40:13.032Z  214535653   1883         1
3           420368  2014-04-04T06:13:28.848Z  214530572   6073         1
4           420368  2014-04-04T06:13:28.858Z  214835025   2617         1
5           140806  2014-04-07T09:22:28.132Z  214668193    523         1
6           140806  2014-04-07T09:22:28.176Z  214587399   1046         1
7           140806  2014-04-07T09:22:28.219Z  214586690    837         1
8           140806  2014-04-07T09:22:28.268Z  214774667   1151         1
9           140806  2014-04-07T09:22:28.280Z  214578823   1046         1
10              11  2014-04-03T11:04:11.417Z  214821371   1046         1
11              11  2014-04-03T11:04:18.097Z  214821371   1046         1
12              12  2014-04-02T10:42:17.227Z  214717867   1778         4
13          489758  2014-04-06T09:59:52.422Z  214826955   1360         2
14          489758  2014-04-06T09:59:52.476Z  214826715    732         2
15          489758  2014-04-06T09:59:52.578Z  214827026   1046         1
16          140802  2014-04-02T16:52:21.678Z  214716984   1883         1
17          489756  2014-04-05T16:51:59.947Z  214716932   6177         1
18          420378  2014-04-03T07:41:02.566Z  214821017   1046         1
19          420378  2014-04-03T07:41:02.616Z  214821020    732         1
20          420378  2014-04-03T07:41:02.668Z  214821013   1883         1
21          281609  2014-04-07T09:25:02.934Z  214821290   1046         4
22          281609  2014-04-07T09:25:06.927Z  214821290   1046         4
23              21  2014-04-07T09:24:18.307Z  214548744   3141         1
24              21  2014-04-07T09:24:18.360Z  214838503  18745         1
25          140826  2014-04-04T06:36:00.009Z  214636775   8375         1
26           70427  2014-04-02T15:54:07.144Z  214820255   3769         1
27              33  2014-04-06T18:24:51.206Z  214834865    523         2
28              33  2014-04-06T18:24:51.207Z  214706441   1360         1
29              33  2014-04-06T18:24:51.207Z  214820225   2092         1
...            ...                       ...        ...    ...       ...
1150723   11539811  2014-09-24T01:01:19.186Z  214701787  13509         2
1150724   11423137  2014-09-25T08:56:53.767Z  214853732   1046         1
1150725   11423151  2014-09-27T16:54:00.897Z  214695225    941         2
1150726   11423151  2014-09-27T16:54:00.960Z  214845356    837         1
1150727   11423151  2014-09-27T16:54:01.091Z  214850945    784         1
1150728   11539734  2014-09-24T10:01:32.582Z  214850945    784         1
1150729   11539734  2014-09-24T10:01:32.590Z  214846014    784         1
1150730   11539734  2014-09-24T10:01:32.595Z  214774674   1674         1
1150731   11399517  2014-09-26T10:33:00.745Z  214849003   2512         1
1150732   11399517  2014-09-26T10:33:00.760Z  214854787    523         2
1150733   11399517  2014-09-26T10:33:00.770Z  214848845   2303         1
1150734   11299794  2014-09-24T19:25:36.882Z  214861498   3664         1
1150735   11299794  2014-09-24T19:25:37.347Z  214861498   3664         1
1150736   11299793  2014-09-25T07:18:35.017Z  214854804   1570         1
1150737   11299793  2014-09-25T07:18:35.082Z  214834933   2093         1
1150738   11523909  2014-09-24T16:50:03.023Z  214853105   1046         1
1150739   11399497  2014-09-24T19:03:19.611Z  214510445   8377         1
1150740   11368652  2014-09-24T12:45:19.052Z  214860155    732         1
1150741   11493056  2014-09-27T12:39:31.238Z  214510445   8377         1
1150742   11523919  2014-09-24T14:35:27.082Z  214704180   8377         1
1150743   11523919  2014-09-24T14:35:27.092Z  214704182   9424         1
1150744   11330173  2014-09-24T07:45:04.886Z  214857204   9424         3
1150745   11330173  2014-09-24T07:45:04.895Z  214857204  12462         1
1150746   11330173  2014-09-24T07:45:04.902Z  214835000   7329         3
1150747   11330173  2014-09-24T07:45:04.953Z  214835000   9424         1
1150748   11368701  2014-09-26T07:52:51.357Z  214849809    554         2
1150749   11368691  2014-09-25T09:37:44.206Z  214700002   6806         5
1150750   11523941  2014-09-25T06:14:47.965Z  214578011  14556         1
1150751   11423202  2014-09-26T18:49:34.024Z  214849164   1046         1
1150752   11423202  2014-09-26T18:49:34.026Z  214560500   5549         1

[1150753 rows x 5 columns]

In [0]:
a_df['timestamp'] =pd.to_datetime(a_df['timestamp'], format="%Y-%m-%d %H:%M:%S.%f")

In [0]:
a_df['timestamp'].head()

0   2014-04-06 18:44:58.314000+00:00
1   2014-04-06 18:44:58.325000+00:00
2   2014-04-06 09:40:13.032000+00:00
3   2014-04-04 06:13:28.848000+00:00
4   2014-04-04 06:13:28.858000+00:00
Name: timestamp, dtype: datetime64[ns, UTC]

In [0]:

a_df['label']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in a_df.quantity]
a_df.head()

   sessionid                        timestamp     itemid  price  quantity label
0     420374 2014-04-06 18:44:58.314000+00:00  214537888  12462         1     1
1     420374 2014-04-06 18:44:58.325000+00:00  214537850  10471         1     1
2     281626 2014-04-06 09:40:13.032000+00:00  214535653   1883         1     1
3     420368 2014-04-04 06:13:28.848000+00:00  214530572   6073         1     1
4     420368 2014-04-04 06:13:28.858000+00:00  214835025   2617         1     1

In [0]:
a_df.sort_values(by=['sessionid'])

         sessionid                        timestamp  ...  quantity  label
11              11 2014-04-03 11:04:18.097000+00:00  ...         1      1
10              11 2014-04-03 11:04:11.417000+00:00  ...         1      1
12              12 2014-04-02 10:42:17.227000+00:00  ...         4      1
23              21 2014-04-07 09:24:18.307000+00:00  ...         1      1
24              21 2014-04-07 09:24:18.360000+00:00  ...         1      1
32              33 2014-04-06 18:24:51.426000+00:00  ...         1      1
29              33 2014-04-06 18:24:51.207000+00:00  ...         1      1
30              33 2014-04-06 18:24:51.295000+00:00  ...         2      1
27              33 2014-04-06 18:24:51.206000+00:00  ...         2      1
28              33 2014-04-06 18:24:51.207000+00:00  ...         1      1
31              33 2014-04-06 18:24:51.422000+00:00  ...         1      1
37              46 2014-04-03 07:09:22.737000+00:00  ...         2      1
38              46 2014-04-03 07:09:22.751000+00:00  ...         1      1
58              87 2014-04-07 06:57:22.749000+00:00  ...         1      1
60              87 2014-04-07 06:57:22.803000+00:00  ...         1      1
57              87 2014-04-07 06:57:22.736000+00:00  ...         1      1
56              87 2014-04-07 06:57:22.679000+00:00  ...         1      1
59              87 2014-04-07 06:57:22.801000+00:00  ...         1      1
55              87 2014-04-07 06:57:22.621000+00:00  ...         1      1
54              87 2014-04-07 06:57:22.557000+00:00  ...         1      1
66             103 2014-04-03 14:26:27.706000+00:00  ...         1      1
105            138 2014-04-04 09:59:42.860000+00:00  ...         1      1
158            181 2014-04-05 11:05:54.507000+00:00  ...         2      1
157            182 2014-04-04 15:02:30.627000+00:00  ...         2      1
156            182 2014-04-04 15:02:14.204000+00:00  ...         2      1
148            189 2014-04-04 07:23:10.719000+00:00  ...         1      1
163            197 2014-04-05 18:19:05.047000+00:00  ...         1      1
177            216 2014-04-02 17:56:01.797000+00:00  ...         4      1
193            253 2014-04-03 20:57:53.988000+00:00  ...         1      1
214            277 2014-04-06 20:52:35.091000+00:00  ...         1      1
...            ...                              ...  ...       ...    ...
1124298   11561722 2014-09-24 06:31:27.078000+00:00  ...         1      1
1124296   11561722 2014-09-24 06:31:27.048000+00:00  ...         2      1
1124295   11561722 2014-09-24 06:31:27.044000+00:00  ...         1      1
1124287   11561722 2014-09-24 06:30:57.890000+00:00  ...         1      1
1124293   11561722 2014-09-24 06:31:27.021000+00:00  ...         2      1
1124292   11561722 2014-09-24 06:30:57.944000+00:00  ...         2      1
1124291   11561722 2014-09-24 06:30:57.921000+00:00  ...         4      1
1124290   11561722 2014-09-24 06:30:57.912000+00:00  ...         1      1
1124294   11561722 2014-09-24 06:31:27.028000+00:00  ...         4      1
1124297   11561722 2014-09-24 06:31:27.058000+00:00  ...         1      1
1124288   11561722 2014-09-24 06:30:57.891000+00:00  ...         2      1
1124289   11561722 2014-09-24 06:30:57.892000+00:00  ...         1      1
1124252   11561779 2014-09-25 12:17:57.190000+00:00  ...         1      1
1124244   11561787 2014-09-26 07:21:57.972000+00:00  ...         1      1
1124245   11561787 2014-09-26 07:21:58.007000+00:00  ...         1      1
1124169   11561814 2014-09-24 18:38:37.597000+00:00  ...         1      1
1124170   11561814 2014-09-24 18:38:37.632000+00:00  ...         1      1
1124186   11561841 2014-09-24 08:36:01.055000+00:00  ...         9      1
1124185   11561841 2014-09-24 08:35:29.656000+00:00  ...         9      1
1124181   11561851 2014-09-26 16:11:38.326000+00:00  ...         1      1
1124111   11561868 2014-09-24 13:39:52.189000+00:00  ...         2      1
1124112   11561868 2014-09-24 13:39:52.232000+00:00  ...         1      1
1124060   11561954 2014-09-25 14:30:38.315000+00:00  ...         2      1
1124081   11561974 2014-09-27 11:00:06.601000+00:00  ...         1      1
1123013   11562097 2014-09-24 17:16:31.433000+00:00  ...         1      1
1123012   11562097 2014-09-24 17:16:30.195000+00:00  ...         1      1
1123018   11562104 2014-09-25 12:32:47.696000+00:00  ...         2      1
1123021   11562106 2014-09-26 10:25:25.079000+00:00  ...         1      1
1122924   11562121 2014-09-25 12:46:36.009000+00:00  ...         1      1
1122923   11562121 2014-09-25 12:46:35.944000+00:00  ...         1      1

[1150753 rows x 6 columns]

In [0]:
a_df_sessionidd=a_df.groupby('sessionid')
a_df_sessionidd

In [0]:
a_df_sessionid_product =a_df.groupby(by = ['sessionid', 'itemid'])['quantity'].sum()
print(a_df_sessionid_product)

sessionid  itemid
11         214821371     2
12         214717867     4
21         214548744     1
           214838503     1
33         214706441     2
           214820225     2
           214834865     4
46         214716932     3
87         214652220     1
           214743369     1
           214819430     1
           214820392     1
           214826837     1
           214826908     1
           214840483     1
103        214748293     1
138        214594592     1
181        214820231     2
182        214535621     4
189        214613865     1
197        214774685     1
216        214821277     4
253        214743341     1
277        214836958     1
           214836960     1
291        214684513     1
293        214821285     1
           214826705     1
           214826803     1
319        214600625     2
                        ..
11561638   214854793     1
11561703   214567327     1
           214567333     1
           214838122     1
           214856707     1
11561717   214849239     1
           214849314     1
           214853310     1
           214854065     1
11561722   214835000     2
           214853102    12
           214853113     2
           214854840     2
           214864880     4
11561779   214510445     1
11561787   214676379     1
           214701305     1
11561814   214712242     1
           214854707     1
11561841   214514317    18
11561851   214854262     1
11561868   214853102     2
           214854787     1
11561954   214854787     2
11561974   214601542     1
11562097   214861498     2
11562104   214844439     2
11562106   214856730     1
11562121   214540691     1
           214839339     1
Name: quantity, Length: 1049817, dtype: int64

In [0]:
a_df_sessionid_product = a_df_sessionid_product.reset_index()             #Dataframe yapısını korumak için reset_index() fonksiyonunu kullanabiliriz. 
HTML(a_df_sessionid_product.to_html())

In [0]:
a_df_sessionid_product

         sessionid     itemid  quantity
0               11  214821371         2
1               12  214717867         4
2               21  214548744         1
3               21  214838503         1
4               33  214706441         2
5               33  214820225         2
6               33  214834865         4
7               46  214716932         3
8               87  214652220         1
9               87  214743369         1
10              87  214819430         1
11              87  214820392         1
12              87  214826837         1
13              87  214826908         1
14              87  214840483         1
15             103  214748293         1
16             138  214594592         1
17             181  214820231         2
18             182  214535621         4
19             189  214613865         1
20             197  214774685         1
21             216  214821277         4
22             253  214743341         1
23             277  214836958         1
24             277  214836960         1
25             291  214684513         1
26             293  214821285         1
27             293  214826705         1
28             293  214826803         1
29             319  214600625         2
...            ...        ...       ...
1049787   11561638  214854793         1
1049788   11561703  214567327         1
1049789   11561703  214567333         1
1049790   11561703  214838122         1
1049791   11561703  214856707         1
1049792   11561717  214849239         1
1049793   11561717  214849314         1
1049794   11561717  214853310         1
1049795   11561717  214854065         1
1049796   11561722  214835000         2
1049797   11561722  214853102        12
1049798   11561722  214853113         2
1049799   11561722  214854840         2
1049800   11561722  214864880         4
1049801   11561779  214510445         1
1049802   11561787  214676379         1
1049803   11561787  214701305         1
1049804   11561814  214712242         1
1049805   11561814  214854707         1
1049806   11561841  214514317        18
1049807   11561851  214854262         1
1049808   11561868  214853102         2
1049809   11561868  214854787         1
1049810   11561954  214854787         2
1049811   11561974  214601542         1
1049812   11562097  214861498         2
1049813   11562104  214844439         2
1049814   11562106  214856730         1
1049815   11562121  214540691         1
1049816   11562121  214839339         1

[1049817 rows x 3 columns]

In [0]:

a_df['label']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in a_df.quantity]
a_df.head()

   sessionid                        timestamp     itemid  price  quantity label
0     420374 2014-04-06 18:44:58.314000+00:00  214537888  12462         1     1
1     420374 2014-04-06 18:44:58.325000+00:00  214537850  10471         1     1
2     281626 2014-04-06 09:40:13.032000+00:00  214535653   1883         1     1
3     420368 2014-04-04 06:13:28.848000+00:00  214530572   6073         1     1
4     420368 2014-04-04 06:13:28.858000+00:00  214835025   2617         1     1

In [0]:
a_df.dtypes

sessionid                  int64
timestamp    datetime64[ns, UTC]
itemid                     int64
price                      int64
quantity                   int64
label                     object
dtype: object

In [0]:
a_df_itemid=a_df.groupby('label')
a_df_itemid
print(a_df_itemid.groups.keys())

dict_keys(['0', '1'])

In [0]:

# Price  ve Quantity değerlerini çarparak toplam tutarı (Amount) bulalım.
A=a_df.sort_values(by=['sessionid'])              #  Session_ID ve Timestamp  a göre sıralanmış veriyi A ifadesine attım ] 


A['Amount'] = A['quantity'] * A['price']
HTML(A.head().to_html())

In [0]:
df_session = A.groupby('sessionid').agg({ 'itemid':'count',          
                                                     'Amount': ['sum','mean'],
                                                    'timestamp': ['min','max' ], 
                                         'quantity':'sum'}).reset_index()

df_session.columns = ['Session_ID','Number_of_Transactions',  'Total_Amount', 'Average_Amount', 'First_Transaction_Date' , 'Last date', 'Quantity']
HTML(df_session.to_html())

In [0]:
df_session.dtypes

Session_ID                              int64
Number_of_Transactions                  int64
Nunique                                 int64
Total_Amount                            int64
Average_Amount                        float64
First_Transaction_Date    datetime64[ns, UTC]
Last date                 datetime64[ns, UTC]
Quantity                                int64
label                                  object
duration                      timedelta64[ns]
dtype: object

In [0]:
df_session.head()

   Session_ID  Number_of_Transactions  ...  label        duration
0          11                       2  ...      1 00:00:06.680000
1          12                       1  ...      1        00:00:00
2          21                       2  ...      1 00:00:00.053000
3          33                       6  ...      1 00:00:00.220000
4          46                       2  ...      1 00:00:00.014000

[5 rows x 9 columns]

In [0]:

a_df_Quantity=a_df.groupby('quantity')
print("quantity") 
print(a_df_Quantity.groups.keys()) 
print("SECTİON sayısı: " + str(a_df_Quantity.ngroups))

quantity
dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 28, 29, 30])
SECTİON sayısı: 28

In [0]:
A=a_df.sort_values(by=['sessionid'])              #  Session_ID ve Timestamp  a göre sıralanmış veriyi A ifadesine attım ] 


A['Amount'] = A['quantity'] * A['price']
HTML(A.head().to_html())





df_session = A.groupby('sessionid').agg({ 'itemid':['count','nunique'],          
                                                     'Amount': ['sum','mean'],
                                                    'timestamp': ['min','max' ], 
                                         'quantity':'sum'}).reset_index()

df_session.columns = ['Session_ID','Number_of_Transactions',  'Nunique', 'Total_Amount', 'Average_Amount', 'First_Transaction_Date' , 'Last date', 'Quantity']
HTML(df_session.to_html())
df_session .head()
df_session['duration'] =( df_session['Last date']- df_session['First_Transaction_Date'])/ np.timedelta64(1, 's')



df_session ['label']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in df_session .Quantity]

df_session.head()

   Session_ID  Number_of_Transactions  Nunique  ...  Quantity  duration label
0          11                       2        1  ...         2     6.680     1
1          12                       1        1  ...         4     0.000     1
2          21                       2        2  ...         2     0.053     1
3          33                       6        3  ...         8     0.220     1
4          46                       2        1  ...         3     0.014     1

[5 rows x 10 columns]

In [0]:
A=df_session.dropna()
A.head()

   Session_ID  Number_of_Transactions  Nunique  ...  Quantity  duration label
0          11                       2        1  ...         2     6.680     1
1          12                       1        1  ...         4     0.000     1
2          21                       2        2  ...         2     0.053     1
3          33                       6        3  ...         8     0.220     1
4          46                       2        1  ...         3     0.014     1

[5 rows x 10 columns]

In [0]:
from pandas import DataFrame



# df = DataFrame(df_session, columns= ['Session_ID',	'Number_of_Transactions', 'Nunique',	'Total_Amount'	, 'Average_Amount',  '	First_Transaction_Date','	Last date',	'Quantity'	,'duration', 'label'])

buy_csv = A.to_csv (r'C:\Users\sevval\Desktop\pandas2\buy_dataframe.csv', header=True) #Don't forget to add '.csv' at the end of the path

                         
A.head()

   Session_ID  Number_of_Transactions  Nunique  ...  Quantity  duration label
0          11                       2        1  ...         2     6.680     1
1          12                       1        1  ...         4     0.000     1
2          21                       2        2  ...         2     0.053     1
3          33                       6        3  ...         8     0.220     1
4          46                       2        1  ...         3     0.014     1

[5 rows x 10 columns]

In [0]:
cA[A['Session_ID'] == 293]

    Session_ID  Number_of_Transactions  Nunique  ...  Quantity  duration label
16         293                       3        3  ...         3     0.113     1

[1 rows x 10 columns]

In [0]:
A.to_csv('buy_csv.csv')
files.download('buy_csv.csv')

In [0]:
################ random forest #################

'n_estimators : integer, optional (default=10)  ''The number of trees in the forest.'

In [0]:
pip install  scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (0.21.2)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (1.16.4)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (1.3.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (0.13.2)

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [0]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd
import os

In [0]:
from google.colab import files
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_list = drive.ListFile({'q': "'10qCLssRuO4QWNFetLr7-iKYXmBsObh97' in parents and trashed=false"}).GetList()
for file1 in file_list:
        print('title: %s, id: %s' % (file1['title'], file1['id']))

#     tra = drive.CreateFile({'id': '1E_IyBNBQIEdKBuhHB9q2npd31jAyIplv'})
#     tra.GetContentFile('event_train_full.txt')

#     tes = drive.CreateFile({'id': '1IAxUAyfwhI-HBU44870czMsZpGPmPdBy'})
#     tes.GetContentFile('event_test.txt')

     |████████████████████████████████| 993kB 3.4MB/s
  Building wheel for PyDrive (setup.py) ... done

In [0]:
tes = drive.CreateFile({'id': '1HQmLPf_GMnRyZMENlG0iTW-V4iIgomqz'})
tes.GetContentFile('buy_csv (1).csv')

In [0]:
tez = drive.CreateFile({'id': '1vFtqNYrhQjhRNX1kPRsRextZG8yOIh9i'})
tez.GetContentFile('abuyss.dat')

In [0]:
newdataset = pd.read_csv('buy_csv (1).csv')

In [0]:
newdataset.head()

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...         2     6.680      1
1           1          12                       1  ...         4     0.000      1
2           2          21                       2  ...         2     0.053      1
3           3          33                       6  ...         8     0.220      1
4           4          46                       2  ...         3     0.014      1

[5 rows x 11 columns]

In [0]:
'########### decision tree yeni #######

In [0]:
newdataset.drop(['First_Transaction_Date'],axis=1).head()
newdataset

        Unnamed: 0  Session_ID  ...  duration  label
0                0          11  ...     6.680      1
1                1          12  ...     0.000      1
2                2          21  ...     0.053      1
3                3          33  ...     0.220      1
4                4          46  ...     0.014      1
5                5          87  ...     0.246      1
6                6         103  ...     0.000      1
7                7         138  ...     0.000      1
8                8         181  ...     0.000      1
9                9         182  ...    16.423      1
10              10         189  ...     0.000      1
11              11         197  ...     0.000      1
12              12         216  ...     0.000      1
13              13         253  ...     0.000      1
14              14         277  ...     0.031      1
15              15         291  ...     0.000      1
16              16         293  ...     0.113      1
17              17         319  ...    60.529      1
18              18         324  ...     0.000      1
19              19         333  ...     0.000      1
20              20         367  ...     1.524      1
21              21         382  ...    13.770      1
22              22         396  ...     0.000      1
23              23         408  ...     9.349      1
24              24         432  ...     0.000      1
25              25         449  ...     0.084      1
26              26         484  ...     3.325      1
27              27         507  ...     0.052      1
28              28         536  ...     0.247      1
29              29         556  ...     0.131      1
...            ...         ...  ...       ...    ...
509666      509666    11561379  ...     0.000      1
509667      509667    11561392  ...     0.016      1
509668      509668    11561393  ...     0.000      1
509669      509669    11561412  ...     0.000      1
509670      509670    11561424  ...     0.081      1
509671      509671    11561448  ...   149.531      1
509672      509672    11561482  ...     0.067      1
509673      509673    11561514  ...     0.061      1
509674      509674    11561538  ...     0.000      1
509675      509675    11561549  ...     0.000      1
509676      509676    11561554  ...     0.000      1
509677      509677    11561572  ...     0.000      1
509678      509678    11561574  ...     0.055      1
509679      509679    11561596  ...     0.052      1
509680      509680    11561638  ...     0.003      1
509681      509681    11561703  ...     0.035      1
509682      509682    11561717  ...     0.122      1
509683      509683    11561722  ...    29.188      1
509684      509684    11561779  ...     0.000      1
509685      509685    11561787  ...     0.035      1
509686      509686    11561814  ...     0.035      1
509687      509687    11561841  ...    31.399      1
509688      509688    11561851  ...     0.000      1
509689      509689    11561868  ...     0.043      1
509690      509690    11561954  ...     0.000      1
509691      509691    11561974  ...     0.000      1
509692      509692    11562097  ...     1.238      1
509693      509693    11562104  ...     0.000      1
509694      509694    11562106  ...     0.000      1
509695      509695    11562121  ...     0.065      1

[509696 rows x 11 columns]

In [0]:


# Bağımlı Değişkeni ( species) bir değişkene atadık
species = newdataset.iloc[:,-1:].values
species

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [0]:
newdataset.iloc[:,1:-1]

        Session_ID  Number_of_Transactions  ...  Quantity  duration
0               11                       2  ...         2     6.680
1               12                       1  ...         4     0.000
2               21                       2  ...         2     0.053
3               33                       6  ...         8     0.220
4               46                       2  ...         3     0.014
5               87                       7  ...         7     0.246
6              103                       1  ...         1     0.000
7              138                       1  ...         1     0.000
8              181                       1  ...         2     0.000
9              182                       2  ...         4    16.423
10             189                       1  ...         1     0.000
11             197                       1  ...         1     0.000
12             216                       1  ...         4     0.000
13             253                       1  ...         1     0.000
14             277                       2  ...         2     0.031
15             291                       1  ...         1     0.000
16             293                       3  ...         3     0.113
17             319                       2  ...         2    60.529
18             324                       1  ...         1     0.000
19             333                       1  ...         1     0.000
20             367                       2  ...         8     1.524
21             382                       2  ...         2    13.770
22             396                       1  ...         1     0.000
23             408                       2  ...         2     9.349
24             432                       1  ...         1     0.000
25             449                       2  ...         2     0.084
26             484                       2  ...         2     3.325
27             507                       2  ...         2     0.052
28             536                       4  ...         4     0.247
29             556                       5  ...        13     0.131
...            ...                     ...  ...       ...       ...
509666    11561379                       1  ...         1     0.000
509667    11561392                       2  ...         2     0.016
509668    11561393                       1  ...         1     0.000
509669    11561412                       1  ...         1     0.000
509670    11561424                       3  ...         3     0.081
509671    11561448                       2  ...         8   149.531
509672    11561482                       3  ...         3     0.067
509673    11561514                       2  ...         2     0.061
509674    11561538                       1  ...         1     0.000
509675    11561549                       1  ...         1     0.000
509676    11561554                       1  ...         1     0.000
509677    11561572                       1  ...         1     0.000
509678    11561574                       2  ...         2     0.055
509679    11561596                       2  ...         2     0.052
509680    11561638                       3  ...         3     0.003
509681    11561703                       4  ...         4     0.035
509682    11561717                       4  ...         4     0.122
509683    11561722                      12  ...        22    29.188
509684    11561779                       1  ...         1     0.000
509685    11561787                       2  ...         2     0.035
509686    11561814                       2  ...         2     0.035
509687    11561841                       2  ...        18    31.399
509688    11561851                       1  ...         1     0.000
509689    11561868                       2  ...         3     0.043
509690    11561954                       1  ...         2     0.000
509691    11561974                       1  ...         1     0.000
509692    11562097                       2  ...         2     1.238
509693    11562104                       1  ...         2     0.000
509694    11562106                       1  ...         1     0.000
509695    11562121                       2  ...         2     0.065

[509696 rows x 9 columns]

In [0]:
c=newdataset.drop(['Last date'],axis=1).head()
c

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...         2     6.680      1
1           1          12                       1  ...         4     0.000      1
2           2          21                       2  ...         2     0.053      1
3           3          33                       6  ...         8     0.220      1
4           4          46                       2  ...         3     0.014      1

[5 rows x 10 columns]

In [0]:
d=newdataset.drop(['First_Transaction_Date'],axis=1).head()
d

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...         2     6.680      1
1           1          12                       1  ...         4     0.000      1
2           2          21                       2  ...         2     0.053      1
3           3          33                       6  ...         8     0.220      1
4           4          46                       2  ...         3     0.014      1

[5 rows x 10 columns]

In [0]:
d.iloc[:,1:-1]

   Session_ID  Number_of_Transactions  ...  Quantity  duration
0          11                       2  ...         2     6.680
1          12                       1  ...         4     0.000
2          21                       2  ...         2     0.053
3          33                       6  ...         8     0.220
4          46                       2  ...         3     0.014

[5 rows x 8 columns]

In [0]:
K=d.dropna()
K.head()

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...         2     6.680      1
1           1          12                       1  ...         4     0.000      1
2           2          21                       2  ...         2     0.053      1
3           3          33                       6  ...         8     0.220      1
4           4          46                       2  ...         3     0.014      1

[5 rows x 10 columns]

In [0]:
# Veri kümemizi test ve train şekinde bölüyoruz
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(K.iloc[:,1:-1],species,test_size=0.33,random_state=0)

# ----------------- Decision Tree ------------------------

# DecisionTreeClassifier sınıfını import ettik
from sklearn.tree import DecisionTreeClassifier

# DecisionTreeClassifier sınıfından bir nesne ürettik
dtc = DecisionTreeClassifier(random_state=0)

# Makineyi eğitiyoruz
dtc.fit(x_train,y_train)

# Test veri kümemizi verdik ve tahmin işlemini gerçekleştirdik
result = dtc.predict(x_test)

from sklearn.metrics import confusion_matrix
# Parametre olarak karşılaştıracağımız verileri giriyoruz.
# y_test : Gerçek test Verisi
# result : x_test verisinden tahmin ettiğimiz veriler
# Confusion Matrix Sonucu :
# [[16  0  0]
#  [ 0 18  1]
#  [ 0  0 15]]
cm = confusion_matrix(y_test,result)
print(cm)

ValueError: ignored

In [0]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, result)
# Sonuç : 0.98
print(accuracy)

# ----------------- Decision Tree ------------------------

# ----------------- Random Forest ------------------------

# RandomForestClassifier sınıfını import ettik
from sklearn.ensemble import RandomForestClassifier

# RandomForestClassifier sınıfından bir nesne ürettik
# n_estimators = Oluşturulacak karar ağacı sayısıdır. Değiştirildiğinde başarı oranıda değişir.
rfc = RandomForestClassifier(n_estimators=4,random_state=0)

# Makineyi eğitiyoruz

rfc.fit(x_train,y_train)

# Test veri kümemizi verdik ve tahmin işlemini gerçekleştirdik
result2 = rfc.predict(x_test)

# Confusion Matrix Sonucu :
# [[16  0  0]
#  [ 0 18  1]
#  [ 0  2 13]]
cm2 = confusion_matrix(y_test,result2)
print(cm2)

# Başarı Oranı
accuracy1 = accuracy_score(y_test, result2)
# Sonuç : 0.94
print(accuracy1)

In [0]:
' ############# RANDOM FOREST

In [0]:
L=Z.dropna()
L.head()

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...       2.0     6.680    1.0
1           1          12                       1  ...       4.0     0.000    1.0
2           2          21                       2  ...       2.0     0.053    1.0
3           3          33                       6  ...       8.0     0.220    1.0
4           4          46                       2  ...       3.0     0.014    1.0

[5 rows x 11 columns]

In [0]:
columNames=['Session_ID', 
             'Number_of_Transactions',	
             'Nunique',	'Total_Amount',	
             'Average_Amount',	'First_Transaction_Date',	
             'Last date', 	'Quantity', 	'duration',	]

In [0]:
print(Z.shape)

(274812, 11)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(Z[columnNames], Z['label'], 
                                                    test_size=0.1, random_state=12)

#Eğer bir random_state değeri belirlersek her seferinde o değere göre böler

In [0]:
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

Number transactions X_train dataset:  (247330, 10)
Number transactions y_train dataset:  (247330,)
Number transactions X_test dataset:  (27482, 10)
Number transactions y_test dataset:  (27482,)
Before OverSampling, counts of label '1': 78566
Before OverSampling, counts of label '0': 168764

In [0]:





X = Z.iloc[:,  [1,2,3,4,]].values
y = Z.iloc[:, 10].values
X
y

array([1., 1., 1., ..., 0., 0., 0.])

In [0]:
from sklearn import cros
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

ValueError: ignored

In [0]:
X = Z.iloc[:,  [1,2,3,4,5,8,9]].values
y = Z.iloc[:, 10].values

In [0]:
X

array([[1.100000e+01, 2.000000e+00, 1.000000e+00, ..., 1.046000e+03,
        2.000000e+00, 6.680000e+00],
       [1.200000e+01, 1.000000e+00, 1.000000e+00, ..., 7.112000e+03,
        4.000000e+00, 0.000000e+00],
       [2.100000e+01, 2.000000e+00, 2.000000e+00, ..., 1.094300e+04,
        2.000000e+00, 5.300000e-02],
       ...,
       [5.978102e+06, 5.000000e+00, 5.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 3.340000e-01],
       [5.978107e+06, 4.000000e+00, 4.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 3.600000e-02],
       [5.978126e+06, 1.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00]])

In [0]:
 y

array([1., 1., 1., ..., 0., 0., 0.])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# 68 bin test geriye kalan train

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [0]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred

array([1., 1., 1., ..., 0., 1., 0.])

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[46909,     0],
       [    0, 21794]])

In [0]:
'#############          decision treeee           #############

In [0]:
species =  B.iloc[:,  [1,2,3,4]].values

In [0]:
c=B.iloc[:, 1:-1 ],
c

In [0]:

species

In [0]:
c=B.iloc[:,-1:]
c.head()

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(  B.iloc[:, 10],species,test_size=0.33,random_state=0)

In [0]:

# DecisionTreeClassifier sınıfını import ettik
from sklearn.tree import DecisionTreeClassifier

# DecisionTreeClassifier sınıfından bir nesne ürettik
dtc = DecisionTreeClassifier(random_state=0)

# Makineyi eğitiyoruz
dtc.fit(x_train,y_train)

# Test veri kümemizi verdik ve tahmin işlemini gerçekleştirdik
result = dtc.predict(x_test)

from sklearn.metrics import confusion_matrix
# Parametre olarak karşılaştıracağımız verileri giriyoruz.
# y_test : Gerçek test Verisi
# result : x_test verisinden tahmin ettiğimiz veriler
# Confusion Matrix Sonucu :
# [[16  0  0]
#  [ 0 18  1]
#  [ 0  0 15]]
cm = confusion_matrix(y_test,result)
print(cm)

In [0]:
'############                  KNN                #################

In [0]:
K=datasett.dropna()
K.head()

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...       2.0     6.680    1.0
1           1          12                       1  ...       4.0     0.000    1.0
2           2          21                       2  ...       2.0     0.053    1.0
3           3          33                       6  ...       8.0     0.220    1.0
4           4          46                       2  ...       3.0     0.014    1.0

[5 rows x 11 columns]

In [0]:
K['First_Transaction_Date'] =pd.to_datetime(K['First_Transaction_Date'], format="%Y-%m-%d %H:%M:%S.%f")
K.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

   Unnamed: 0  Session_ID  Number_of_Transactions  ...  Quantity  duration  label
0           0          11                       2  ...       2.0     6.680    1.0
1           1          12                       1  ...       4.0     0.000    1.0
2           2          21                       2  ...       2.0     0.053    1.0
3           3          33                       6  ...       8.0     0.220    1.0
4           4          46                       2  ...       3.0     0.014    1.0

[5 rows x 11 columns]

In [0]:
X = K.iloc[:,  [1,2,3,4,5,8,9]].values
y = K.iloc[:, 10].values
X

#X = array[:,0:41]
#Y = array[:,41]

array([[1.100000e+01, 2.000000e+00, 1.000000e+00, ..., 1.046000e+03,
        2.000000e+00, 6.680000e+00],
       [1.200000e+01, 1.000000e+00, 1.000000e+00, ..., 7.112000e+03,
        4.000000e+00, 0.000000e+00],
       [2.100000e+01, 2.000000e+00, 2.000000e+00, ..., 1.094300e+04,
        2.000000e+00, 5.300000e-02],
       ...,
       [5.978102e+06, 5.000000e+00, 5.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 3.340000e-01],
       [5.978107e+06, 4.000000e+00, 4.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 3.600000e-02],
       [5.978126e+06, 1.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00]])

In [0]:
from sklearn.model_selection import train_test_split #Veri setinde 400 kayıt var bunun 300’ünü eğitim, 100’ünü test için ayıralım.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [0]:

from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[46909     0]
 [    7 21787]]

In [0]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9998981121639521

In [0]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('orange', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
     plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                 c = ListedColormap(('yellow', 'green'))(i), label = j)
plt.title('K En Yakın Komşu (test seti)')
plt.xlabel('Session_ID')
plt.ylabel('duration')
plt.legend()
plt.show()

In [0]:
'################## itemid ###############

In [0]:
from google.colab import files
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_list = drive.ListFile({'q': "'1vFtqNYrhQjhRNX1kPRsRextZG8yOIh9i' in parents and trashed=false"}).GetList()
for file1 in file_list:
        print('title: %s, id: %s' % (file1['title'], file1['id']))

#     tra = drive.CreateFile({'id': '1E_IyBNBQIEdKBuhHB9q2npd31jAyIplv'})
#     tra.GetContentFile('event_train_full.txt')

#     tes = drive.CreateFile({'id': '1IAxUAyfwhI-HBU44870czMsZpGPmPdBy'})
#     tes.GetContentFile('event_test.txt')

# drive okuma

In [0]:
tes = drive.CreateFile({'id': '1vFtqNYrhQjhRNX1kPRsRextZG8yOIh9i'})
tes.GetContentFile('abuyss.dat')

In [0]:
abuys=pd.read_csv('abuyss.dat')

In [0]:
abuys.head()

   sessionid                 timestamp     itemid  price  quantity
0     420374  2014-04-06T18:44:58.314Z  214537888  12462         1
1     420374  2014-04-06T18:44:58.325Z  214537850  10471         1
2     281626  2014-04-06T09:40:13.032Z  214535653   1883         1
3     420368  2014-04-04T06:13:28.848Z  214530572   6073         1
4     420368  2014-04-04T06:13:28.858Z  214835025   2617         1

In [0]:
A=abuys.sort_values(by=['itemid'])

In [0]:
A

         sessionid                 timestamp      itemid  price  quantity
1113461   10801742  2014-09-17T16:20:16.660Z   214507331   3141         1
13083       291086  2014-04-07T18:18:05.867Z   214507331   3141         1
737672     7595866  2014-08-06T04:46:35.160Z   214507331      0         0
442144     4827031  2014-06-13T20:30:39.474Z   214507331      0         0
636735     6207674  2014-07-17T08:26:55.062Z   214507331      0         0
672244     6613316  2014-07-23T08:08:06.550Z   214507331      0         0
319361     3306326  2014-05-21T12:47:00.120Z   214507331      0         0
1133943   11318881  2014-09-26T12:44:37.238Z   214507331   3141         1
671686     6986928  2014-07-23T18:59:51.142Z   214507331      0         0
13165       290993  2014-04-05T07:01:41.720Z   214507331   3141         1
13166       290993  2014-04-05T07:03:51.063Z   214507331   3141         1
98040      1246822  2014-04-18T14:03:47.417Z   214507331   3141         1
28500       384209  2014-04-02T13:13:29.622Z   214507331   3141         1
513266     5495671  2014-06-25T09:27:29.149Z   214507331      0         0
639483     6524036  2014-07-18T15:06:46.374Z   214507331      0         0
786805     8025403  2014-08-17T11:47:38.863Z   214507331   3141         1
1059919   10653448  2014-09-13T12:44:20.838Z   214507331   3141         1
135027     1395546  2014-04-28T22:03:07.103Z   214507331   3141         1
257814     2423893  2014-05-12T11:14:57.922Z   214507331      0         0
425079     4453389  2014-06-16T18:52:02.099Z   214507331      0         0
49911       841057  2014-04-14T17:16:26.115Z   214507331   3141         1
867576     8665227  2014-08-20T16:59:36.006Z   214507331   3141         1
512222     5303011  2014-06-25T12:31:44.267Z   214507331      0         0
1137465   11263266  2014-09-26T14:52:22.054Z   214507331   3141         1
1137466   11263266  2014-09-26T14:52:45.017Z   214507331   3141         1
98025      1219819  2014-04-21T15:00:07.650Z   214507331   3141         1
318178     3374248  2014-05-23T20:02:56.246Z   214507331      0         0
28499       384209  2014-04-02T13:12:49.816Z   214507331   3141         1
90075       922448  2014-04-08T16:31:19.435Z   214507331   3141         1
443842     4550122  2014-06-10T19:12:40.407Z   214507331      0         0
...            ...                       ...         ...    ...       ...
230567     2219878  2014-05-08T08:26:57.259Z   643078950      0         0
223039     2387007  2014-05-07T12:32:16.671Z   643078950      0         0
230568     2219878  2014-05-08T08:32:25.831Z   643078950      0         0
223044     2387007  2014-05-07T12:40:05.594Z   643078950      0         0
223043     2387007  2014-05-07T12:36:11.119Z   643078950      0         0
223040     2387007  2014-05-07T12:33:51.653Z   643078950      0         0
230571     2219878  2014-05-08T08:43:32.609Z   643078950      0         0
230569     2219878  2014-05-08T08:35:22.196Z   643078950      0         0
251784     2414599  2014-05-07T12:12:10.350Z   643078950      0         0
223035     2387007  2014-05-07T12:27:11.853Z   643078950      0         0
251785     2414599  2014-05-07T12:14:35.028Z   643078950      0         0
251782     2414599  2014-05-07T12:07:23.685Z   643078950      0         0
251786     2414599  2014-05-07T12:18:52.865Z   643078950      0         0
251788     2414599  2014-05-07T12:31:01.789Z   643078950      0         0
251789     2414599  2014-05-07T12:34:45.302Z   643078950      0         0
251790     2414599  2014-05-07T12:38:19.707Z   643078950      0         0
251791     2414599  2014-05-07T13:32:07.704Z   643078950      0         0
251793     2414599  2014-05-07T13:41:59.525Z   643078950      0         0
223036     2387007  2014-05-07T12:30:02.895Z   643078950      0         0
251461     2625166  2014-05-07T12:11:46.053Z   643078950      0         0
223031     2387007  2014-05-07T12:15:07.306Z   643078950      0         0
223032     2387007  2014-05-07T12:17:55.276Z   643078950      0         0
276052     3002687  2014-05-15T16:14:36.932Z   643078950      0         0
223033     2387007  2014-05-07T12:19:56.415Z   643078950      0         0
223034     2387007  2014-05-07T12:24:14.897Z   643078950      0         0
251462     2625166  2014-05-07T12:12:53.933Z   643078950      0         0
251783     2414599  2014-05-07T12:08:50.836Z   643078950      0         0
255876     2613153  2014-05-08T10:02:33.442Z  1178818815      0         0
255877     2613152  2014-05-08T08:13:51.245Z  1178825045      0         0
255878     2613152  2014-05-08T08:16:21.155Z  1178837797      0         0

[1150753 rows x 5 columns]

In [0]:
C=abuys.groupby('itemid')
print("itemid") 
print(C.groups.keys()) 
print("SECTİON sayısı: " + str(C.ngroups))

itemid

In [0]:
E=abuys.groupby('quantity')

print(E.groups.keys()) 
print("SECTİON sayısı: " + str(E.ngroups))

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 28, 29, 30])
SECTİON sayısı: 28

In [0]:
D=A[A['itemid'] == 214507331]

In [0]:
D.head()

         sessionid                 timestamp     itemid  ...  quantity  STATE LABEL
1113461   10801742  2014-09-17T16:20:16.660Z  214507331  ...         1      1     1
13083       291086  2014-04-07T18:18:05.867Z  214507331  ...         1      1     1
737672     7595866  2014-08-06T04:46:35.160Z  214507331  ...         0      0     0
442144     4827031  2014-06-13T20:30:39.474Z  214507331  ...         0      0     0
636735     6207674  2014-07-17T08:26:55.062Z  214507331  ...         0      0     0

[5 rows x 7 columns]

In [0]:
 A['STATE']=['+'
                                      if sayii==214507331
                                      else '-'
                                       
                                      for sayii in A.itemid]

A.head()

         sessionid                 timestamp     itemid  ...  quantity  label STATE
1113461   10801742  2014-09-17T16:20:16.660Z  214507331  ...         1      -     +
13083       291086  2014-04-07T18:18:05.867Z  214507331  ...         1      -     +
737672     7595866  2014-08-06T04:46:35.160Z  214507331  ...         0      -     +
442144     4827031  2014-06-13T20:30:39.474Z  214507331  ...         0      -     +
636735     6207674  2014-07-17T08:26:55.062Z  214507331  ...         0      -     +

[5 rows x 7 columns]

In [0]:
A.drop(['label'],axis=1).head()

         sessionid                 timestamp     itemid  price  quantity STATE
1113461   10801742  2014-09-17T16:20:16.660Z  214507331   3141         1     +
13083       291086  2014-04-07T18:18:05.867Z  214507331   3141         1     +
737672     7595866  2014-08-06T04:46:35.160Z  214507331      0         0     +
442144     4827031  2014-06-13T20:30:39.474Z  214507331      0         0     +
636735     6207674  2014-07-17T08:26:55.062Z  214507331      0         0     +

In [0]:
D['LABEL']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in D.quantity]

D.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

         sessionid                 timestamp     itemid  ...  quantity  STATE LABEL
1113461   10801742  2014-09-17T16:20:16.660Z  214507331  ...         1      1     1
13083       291086  2014-04-07T18:18:05.867Z  214507331  ...         1      1     1
737672     7595866  2014-08-06T04:46:35.160Z  214507331  ...         0      0     0
442144     4827031  2014-06-13T20:30:39.474Z  214507331  ...         0      0     0
636735     6207674  2014-07-17T08:26:55.062Z  214507331  ...         0      0     0

[5 rows x 7 columns]

In [0]:
Aitemid=A.groupby('itemid')
Aitemid

In [0]:
Aitemid

In [0]:
a_df_itemid_product =A.groupby(by = [ 'itemid','sessionid'])
print(a_df_itemid_product)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fcbf8cb3390>

In [0]:
a_df_itemid_product.head()

In [0]:
a_df_itemid_product

In [0]:
a_df_itemid_product

In [0]:
itemidd['new']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in itemidd.quantity

itemidd.head()

SyntaxError: ignored

In [0]:
^'####################newdataset############

In [0]:
newdataset

         sessionid                        timestamp     itemid  price  quantity
0           420374 2014-04-06 18:44:58.314000+00:00  214537888  12462         1
1           420374 2014-04-06 18:44:58.325000+00:00  214537850  10471         1
2           281626 2014-04-06 09:40:13.032000+00:00  214535653   1883         1
3           420368 2014-04-04 06:13:28.848000+00:00  214530572   6073         1
4           420368 2014-04-04 06:13:28.858000+00:00  214835025   2617         1
5           140806 2014-04-07 09:22:28.132000+00:00  214668193    523         1
6           140806 2014-04-07 09:22:28.176000+00:00  214587399   1046         1
7           140806 2014-04-07 09:22:28.219000+00:00  214586690    837         1
8           140806 2014-04-07 09:22:28.268000+00:00  214774667   1151         1
9           140806 2014-04-07 09:22:28.280000+00:00  214578823   1046         1
10              11 2014-04-03 11:04:11.417000+00:00  214821371   1046         1
11              11 2014-04-03 11:04:18.097000+00:00  214821371   1046         1
12              12 2014-04-02 10:42:17.227000+00:00  214717867   1778         4
13          489758 2014-04-06 09:59:52.422000+00:00  214826955   1360         2
14          489758 2014-04-06 09:59:52.476000+00:00  214826715    732         2
15          489758 2014-04-06 09:59:52.578000+00:00  214827026   1046         1
16          140802 2014-04-02 16:52:21.678000+00:00  214716984   1883         1
17          489756 2014-04-05 16:51:59.947000+00:00  214716932   6177         1
18          420378 2014-04-03 07:41:02.566000+00:00  214821017   1046         1
19          420378 2014-04-03 07:41:02.616000+00:00  214821020    732         1
20          420378 2014-04-03 07:41:02.668000+00:00  214821013   1883         1
21          281609 2014-04-07 09:25:02.934000+00:00  214821290   1046         4
22          281609 2014-04-07 09:25:06.927000+00:00  214821290   1046         4
23              21 2014-04-07 09:24:18.307000+00:00  214548744   3141         1
24              21 2014-04-07 09:24:18.360000+00:00  214838503  18745         1
25          140826 2014-04-04 06:36:00.009000+00:00  214636775   8375         1
26           70427 2014-04-02 15:54:07.144000+00:00  214820255   3769         1
27              33 2014-04-06 18:24:51.206000+00:00  214834865    523         2
28              33 2014-04-06 18:24:51.207000+00:00  214706441   1360         1
29              33 2014-04-06 18:24:51.207000+00:00  214820225   2092         1
...            ...                              ...        ...    ...       ...
1150723   11539811 2014-09-24 01:01:19.186000+00:00  214701787  13509         2
1150724   11423137 2014-09-25 08:56:53.767000+00:00  214853732   1046         1
1150725   11423151 2014-09-27 16:54:00.897000+00:00  214695225    941         2
1150726   11423151 2014-09-27 16:54:00.960000+00:00  214845356    837         1
1150727   11423151 2014-09-27 16:54:01.091000+00:00  214850945    784         1
1150728   11539734 2014-09-24 10:01:32.582000+00:00  214850945    784         1
1150729   11539734 2014-09-24 10:01:32.590000+00:00  214846014    784         1
1150730   11539734 2014-09-24 10:01:32.595000+00:00  214774674   1674         1
1150731   11399517 2014-09-26 10:33:00.745000+00:00  214849003   2512         1
1150732   11399517 2014-09-26 10:33:00.760000+00:00  214854787    523         2
1150733   11399517 2014-09-26 10:33:00.770000+00:00  214848845   2303         1
1150734   11299794 2014-09-24 19:25:36.882000+00:00  214861498   3664         1
1150735   11299794 2014-09-24 19:25:37.347000+00:00  214861498   3664         1
1150736   11299793 2014-09-25 07:18:35.017000+00:00  214854804   1570         1
1150737   11299793 2014-09-25 07:18:35.082000+00:00  214834933   2093         1
1150738   11523909 2014-09-24 16:50:03.023000+00:00  214853105   1046         1
1150739   11399497 2014-09-24 19:03:19.611000+00:00  214510445   8377         1
1150740   11368652 2014-09-24 12:45:19.052000+00:00  214860155    732         1
1150741   11493056 2014-09-27 12:39:31.238000+00:00  214510445   8377         1
1150742   11523919 2014-09-24 14:35:27.082000+00:00  214704180   8377         1
1150743   11523919 2014-09-24 14:35:27.092000+00:00  214704182   9424         1
1150744   11330173 2014-09-24 07:45:04.886000+00:00  214857204   9424         3
1150745   11330173 2014-09-24 07:45:04.895000+00:00  214857204  12462         1
1150746   11330173 2014-09-24 07:45:04.902000+00:00  214835000   7329         3
1150747   11330173 2014-09-24 07:45:04.953000+00:00  214835000   9424         1
1150748   11368701 2014-09-26 07:52:51.357000+00:00  214849809    554         2
1150749   11368691 2014-09-25 09:37:44.206000+00:00  214700002   6806         5
1150750   11523941 2014-09-25 06:14:47.965000+00:00  214578011  14556         1
1150751   11423202 2014-09-26 18:49:34.024000+00:00  214849164   1046         1
1150752   11423202 2014-09-26 18:49:34.026000+00:00  214560500   5549         1

[1150753 rows x 5 columns]

In [0]:
newdataset['timestamp'] =pd.to_datetime(newdataset['timestamp'], format="%Y-%m-%d %H:%M:%S.%f")

In [0]:
A=newdataset.sort_values(by=['timestamp'])

In [0]:
A

         sessionid                        timestamp     itemid  price  quantity
15774       263073 2014-04-01 03:05:31.743000+00:00  214716982   2617         1
20274       466654 2014-04-01 03:21:30.255000+00:00  214820812    313         1
20275       466654 2014-04-01 03:21:30.271000+00:00  214584907   4711         1
48952       185089 2014-04-01 03:29:09.230000+00:00  214819376    418         1
48953       185089 2014-04-01 03:29:09.280000+00:00  214819430    418         1
48954       185089 2014-04-01 03:29:09.375000+00:00  214716667    627         1
48955       185089 2014-04-01 03:29:09.422000+00:00  214819762    627         1
48956       185089 2014-04-01 03:29:09.446000+00:00  214819760    627         1
46089       306892 2014-04-01 03:43:55.867000+00:00  214842420    889         3
46090       306892 2014-04-01 03:43:55.907000+00:00  214842577    931         2
11796       138708 2014-04-01 03:43:56.545000+00:00  214717007   2303         2
10478        74343 2014-04-01 03:44:41.288000+00:00  214840483   1674         1
11370       293141 2014-04-01 03:45:27.958000+00:00  214826874   1046         1
11371       293141 2014-04-01 03:45:27.969000+00:00  214821399    941         1
11372       293141 2014-04-01 03:46:01.279000+00:00  214826874   1046         1
11373       293141 2014-04-01 03:46:01.281000+00:00  214821399    941         1
48850       494924 2014-04-01 03:51:56.923000+00:00  214832559   2092         1
48851       494924 2014-04-01 03:51:56.925000+00:00  214832557   2092         1
5348          6294 2014-04-01 03:53:05.385000+00:00  214696434  31311         1
35863       385286 2014-04-01 03:55:15.808000+00:00  214840483   1674         1
28618       243689 2014-04-01 03:58:22.472000+00:00  214826893    627         2
28619       243689 2014-04-01 03:58:22.480000+00:00  214826844   1570         2
5349          6294 2014-04-01 03:59:32.049000+00:00  214696434  31311         1
24525        90821 2014-04-01 04:01:08.749000+00:00  214580413  19792         1
42240       193126 2014-04-01 04:12:10.841000+00:00  214690792   1570         1
21850       340109 2014-04-01 04:13:09.641000+00:00  214667912    941         1
21851       340109 2014-04-01 04:13:09.644000+00:00  214748336   1046         1
21852       340109 2014-04-01 04:13:09.648000+00:00  214601233    627         1
21853       340109 2014-04-01 04:13:09.654000+00:00  214820400    418         1
34166       111337 2014-04-01 04:13:52.165000+00:00  214567052   5235         1
...            ...                              ...        ...    ...       ...
1123903   11339173 2014-09-30 01:21:23.598000+00:00  214606952   2093         1
1123904   11339173 2014-09-30 01:21:23.652000+00:00  214856550   1046         1
1123905   11339173 2014-09-30 01:21:23.656000+00:00  214857757   1570         1
1123906   11339173 2014-09-30 01:21:23.669000+00:00  214855982    418         1
1137333   11555513 2014-09-30 01:32:31.223000+00:00  214849327   9947         1
1137334   11555513 2014-09-30 01:32:32.896000+00:00  214849327   9947         1
1144531   11500778 2014-09-30 01:51:13.135000+00:00  214857568   1046         1
1144532   11500778 2014-09-30 01:51:13.231000+00:00  214857570   1360         1
1144533   11500778 2014-09-30 01:51:13.245000+00:00  214857562    627         1
1144086   11391378 2014-09-30 01:54:53.464000+00:00  214858847   1570         1
1144087   11391378 2014-09-30 01:54:53.519000+00:00  214858905    627         1
1143188   11500176 2014-09-30 01:59:29.621000+00:00  214844439   2093         2
1143189   11500176 2014-09-30 01:59:29.993000+00:00  214844439   2093         2
1150635   11453627 2014-09-30 01:59:50.654000+00:00  214708372   1046         1
1143190   11500176 2014-09-30 02:09:28.907000+00:00  214857568   1046         2
1143191   11500176 2014-09-30 02:09:28.909000+00:00  214847724   1046         1
1143192   11500176 2014-09-30 02:09:28.915000+00:00  214855012    313         1
1143193   11500176 2014-09-30 02:09:29.258000+00:00  214857568   1046         2
1143194   11500176 2014-09-30 02:09:29.362000+00:00  214855012    313         1
1143195   11500176 2014-09-30 02:09:29.362000+00:00  214847724   1046         1
1146382   11335313 2014-09-30 02:10:14.800000+00:00  214859859   1046         1
1146383   11335313 2014-09-30 02:10:15.053000+00:00  214859859   1046         1
1132413   11552533 2014-09-30 02:33:22.151000+00:00  214829840    290         2
1132414   11552533 2014-09-30 02:33:22.213000+00:00  214854915    365         2
1132415   11552533 2014-09-30 02:33:22.271000+00:00  214855659     58         4
1132416   11552533 2014-09-30 02:33:22.344000+00:00  214856250    116         1
1123897   11339174 2014-09-30 02:35:12.855000+00:00  214844347   1046         1
1123898   11339174 2014-09-30 02:35:12.856000+00:00  214845583    784         1
1123899   11339174 2014-09-30 02:35:12.858000+00:00  214857774   2093         1
1123900   11339174 2014-09-30 02:35:12.859000+00:00  214850788   1151         1

[1150753 rows x 5 columns]

In [0]:
A['LABEL']=['0'
                                      if sayii<1
                                      else '1'
                                      for sayii in A.quantity]

A

         sessionid                        timestamp  ...  quantity  LABEL
15774       263073 2014-04-01 03:05:31.743000+00:00  ...         1      1
20274       466654 2014-04-01 03:21:30.255000+00:00  ...         1      1
20275       466654 2014-04-01 03:21:30.271000+00:00  ...         1      1
48952       185089 2014-04-01 03:29:09.230000+00:00  ...         1      1
48953       185089 2014-04-01 03:29:09.280000+00:00  ...         1      1
48954       185089 2014-04-01 03:29:09.375000+00:00  ...         1      1
48955       185089 2014-04-01 03:29:09.422000+00:00  ...         1      1
48956       185089 2014-04-01 03:29:09.446000+00:00  ...         1      1
46089       306892 2014-04-01 03:43:55.867000+00:00  ...         3      1
46090       306892 2014-04-01 03:43:55.907000+00:00  ...         2      1
11796       138708 2014-04-01 03:43:56.545000+00:00  ...         2      1
10478        74343 2014-04-01 03:44:41.288000+00:00  ...         1      1
11370       293141 2014-04-01 03:45:27.958000+00:00  ...         1      1
11371       293141 2014-04-01 03:45:27.969000+00:00  ...         1      1
11372       293141 2014-04-01 03:46:01.279000+00:00  ...         1      1
11373       293141 2014-04-01 03:46:01.281000+00:00  ...         1      1
48850       494924 2014-04-01 03:51:56.923000+00:00  ...         1      1
48851       494924 2014-04-01 03:51:56.925000+00:00  ...         1      1
5348          6294 2014-04-01 03:53:05.385000+00:00  ...         1      1
35863       385286 2014-04-01 03:55:15.808000+00:00  ...         1      1
28618       243689 2014-04-01 03:58:22.472000+00:00  ...         2      1
28619       243689 2014-04-01 03:58:22.480000+00:00  ...         2      1
5349          6294 2014-04-01 03:59:32.049000+00:00  ...         1      1
24525        90821 2014-04-01 04:01:08.749000+00:00  ...         1      1
42240       193126 2014-04-01 04:12:10.841000+00:00  ...         1      1
21850       340109 2014-04-01 04:13:09.641000+00:00  ...         1      1
21851       340109 2014-04-01 04:13:09.644000+00:00  ...         1      1
21852       340109 2014-04-01 04:13:09.648000+00:00  ...         1      1
21853       340109 2014-04-01 04:13:09.654000+00:00  ...         1      1
34166       111337 2014-04-01 04:13:52.165000+00:00  ...         1      1
...            ...                              ...  ...       ...    ...
1123903   11339173 2014-09-30 01:21:23.598000+00:00  ...         1      1
1123904   11339173 2014-09-30 01:21:23.652000+00:00  ...         1      1
1123905   11339173 2014-09-30 01:21:23.656000+00:00  ...         1      1
1123906   11339173 2014-09-30 01:21:23.669000+00:00  ...         1      1
1137333   11555513 2014-09-30 01:32:31.223000+00:00  ...         1      1
1137334   11555513 2014-09-30 01:32:32.896000+00:00  ...         1      1
1144531   11500778 2014-09-30 01:51:13.135000+00:00  ...         1      1
1144532   11500778 2014-09-30 01:51:13.231000+00:00  ...         1      1
1144533   11500778 2014-09-30 01:51:13.245000+00:00  ...         1      1
1144086   11391378 2014-09-30 01:54:53.464000+00:00  ...         1      1
1144087   11391378 2014-09-30 01:54:53.519000+00:00  ...         1      1
1143188   11500176 2014-09-30 01:59:29.621000+00:00  ...         2      1
1143189   11500176 2014-09-30 01:59:29.993000+00:00  ...         2      1
1150635   11453627 2014-09-30 01:59:50.654000+00:00  ...         1      1
1143190   11500176 2014-09-30 02:09:28.907000+00:00  ...         2      1
1143191   11500176 2014-09-30 02:09:28.909000+00:00  ...         1      1
1143192   11500176 2014-09-30 02:09:28.915000+00:00  ...         1      1
1143193   11500176 2014-09-30 02:09:29.258000+00:00  ...         2      1
1143194   11500176 2014-09-30 02:09:29.362000+00:00  ...         1      1
1143195   11500176 2014-09-30 02:09:29.362000+00:00  ...         1      1
1146382   11335313 2014-09-30 02:10:14.800000+00:00  ...         1      1
1146383   11335313 2014-09-30 02:10:15.053000+00:00  ...         1      1
1132413   11552533 2014-09-30 02:33:22.151000+00:00  ...         2      1
1132414   11552533 2014-09-30 02:33:22.213000+00:00  ...         2      1
1132415   11552533 2014-09-30 02:33:22.271000+00:00  ...         4      1
1132416   11552533 2014-09-30 02:33:22.344000+00:00  ...         1      1
1123897   11339174 2014-09-30 02:35:12.855000+00:00  ...         1      1
1123898   11339174 2014-09-30 02:35:12.856000+00:00  ...         1      1
1123899   11339174 2014-09-30 02:35:12.858000+00:00  ...         1      1
1123900   11339174 2014-09-30 02:35:12.859000+00:00  ...         1      1

[1150753 rows x 6 columns]

In [0]:
filtre1=A.timestamp> 
filtre2=Kalori_Cetveli_DF.miktar>50

Kalori_Cetveli_DF[filtre1&filtre2]

In [0]:
a_df_itemid=A.groupby('LABEL')
a_df_itemid
print(a_df_itemid.groups.keys())

NameError: ignored

In [0]:
X = A.iloc[:, [0,2,3,4]].values
y =A.iloc[:, 5].values

In [0]:
y

array(['1', '1', '1', ..., '1', '1', '1'], dtype=object)

In [0]:
!pip install scikit-learn
!pip  install  tensorflow

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (0.21.2)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (1.3.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (0.13.2)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn) (1.16.4)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.6/dist-packages (1.14.0)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.8.0)
Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.2.2)
Requirement already satisfied: numpy<2.0,>=1.14.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.16.4)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (3.7.1)
Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.14.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.33.4)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.15.0)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.7.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.1.0)
Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.0.8)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.11.2)
Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.14.0)
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.1.7)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.6.1->tensorflow) (41.0.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (0.15.4)
Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.6->tensorflow) (2.8.0)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[152767      0]
 [     0 134922]]